name: catalogo_filmes
description: Um aplicativo para catalogar filmes com uma interface moderna.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.5
  flutter_spinkit: ^5.2.1
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^1.0.1+1  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true