name: lista_tarefas
description: Um aplicativo de lista de tarefas com prioridade.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true